name: UNIT_TEST

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Prepare the environment
      run: cp .env.example .env
    - name: Install Composer dependencies
      run: composer install --prefer-dist
    - name: Run key generate
      run: php artisan key:generate
    - name: Run tests
      run: php vendor/bin/phpunit
    - name: Notify result to slack
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*UNIT TEST*'
        channel: '#post-bk-develop'
        icon_emoji: https://meigen.keiziban-jp.com/wp-content/uploads/2016/04/kote2.jpg
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
