name: UNIT_TEST

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run phpunit
      run: php vendor/bin/phpunit
