name: UNIT_TEST

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Prepare the environment
      run: cp .env.example .env
    - name: Install Composer dependencies
      run: composer install --prefer-dist
    - name: Run key generate
      run: php artisan key:generate
    - name: Run tests
      run: php vendor/bin/phpunit
